version: '3.9'

services:
  telegram-bot:
    build: .
    container_name: telegram_summarizer_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
